name: airwatch_socket_workaround
description: A workaround for AirWatch MDM Socket problem using dart sockets
version: 0.0.4
repository: https://github.com/GoncaloPT/airwatch_socket_workaround

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  logging: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  http_parser: ^4.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: AirwatchSocketWorkaroundPlugin